/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package servitrans;

import DB.ventas;
import java.awt.event.KeyEvent;
import tools.Util;
import tools.ifWindowsOpen;
import tools.msj;
import ventas.buscarArticulo;

/**
 *
 * @author Tecnologer
 */
public class venta extends javax.swing.JInternalFrame {

    public static String nb_usuario="Sistemas";
    public static boolean isNewVenta;
    public static boolean isTotalizada;
    public static buscarArticulo bArt=new buscarArticulo(null, true);
    public venta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_venta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        agregarVenta = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fc_venta = new javax.swing.JLabel();
        us_venta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cantArticulos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        montoVenta = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cajero: "+Session.usuario);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                activarBtn(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                llenarTabla(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CODIGO:");

        txt_codigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigoagregarProducto(evt);
            }
        });

        agregarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        agregarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarVentaActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tablaVenta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripción", "Precio", "Cantidad", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaVenta.setDragEnabled(true);
        tablaVenta.setGridColor(new java.awt.Color(204, 204, 255));
        tablaVenta.setShowHorizontalLines(false);
        tablaVenta.setShowVerticalLines(false);
        tablaVenta.getTableHeader().setResizingAllowed(false);
        tablaVenta.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaVenta);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Usuario:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Fecha:");

        fc_venta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fc_venta.setText(Session.fecha);

        us_venta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        us_venta.setText(Session.usuario);

        javax.swing.GroupLayout user_ventaLayout = new javax.swing.GroupLayout(user_venta);
        user_venta.setLayout(user_ventaLayout);
        user_ventaLayout.setHorizontalGroup(
            user_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_ventaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(user_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(user_ventaLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                        .addGroup(user_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(user_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fc_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(us_venta, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jScrollPane1)))
        );
        user_ventaLayout.setVerticalGroup(
            user_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_ventaLayout.createSequentialGroup()
                .addGroup(user_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(user_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(user_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(user_ventaLayout.createSequentialGroup()
                                .addGroup(user_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(us_venta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(user_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(fc_venta)))
                            .addGroup(user_ventaLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, user_ventaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(agregarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txt_codigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        cantArticulos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cantArticulos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cantArticulos.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Total:");

        montoVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        montoVenta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        montoVenta.setText("$ 0.00");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Articulos:  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 578, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(montoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cantArticulos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(montoVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(user_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 528, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(user_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(81, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pago(java.awt.event.KeyEvent evt) {                      
        int art=Integer.parseInt(cantArticulos.getText());
        
        if(art>0)
        {
            String monto;
                String montoVent=Util.quitarFormatoMoneda(montoVenta.getText());
                monto=txt_codigo.getText();
                if(monto.equals(""))
                   monto=Util.quitarFormatoMoneda(montoVenta.getText());
                //TOTALIZAR VENTA
                if(evt.getKeyCode() == KeyEvent.VK_F1)
                    BRO.venta.totalizarVenta(montoVenta.getText());
                //EFECTIVO
                else if (evt.getKeyCode() == KeyEvent.VK_F2) 
                {
                    if(isTotalizada)
                        MNG.pagos.recibirPago(monto, montoVent, '1');                   
                    else
                        msj.ms("Finalizar", "Finalice cuenta con F1", msj.info);
                        
                }
                //TARJETA
                else if (evt.getKeyCode() == KeyEvent.VK_F3)
                {
                    if(isTotalizada)
                        MNG.pagos.recibirPago(monto, montoVent, '2');
                    else
                        msj.ms("Finalizar", "Finalice cuenta con F1", msj.info);
                }
            }
    }
    private void txt_codigoagregarProducto(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoagregarProducto
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {            
            agregarVentaActionPerformed(null);
        } else {
            pago(evt);
        }
    }//GEN-LAST:event_txt_codigoagregarProducto

    private void agregarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarVentaActionPerformed
        String codigo=txt_codigo.getText();
        if(!codigo.equals(""))
        {
            newventa();
            MNG.lineaVenta.nueva(codigo);
        }
    }//GEN-LAST:event_agregarVentaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        bArt.setLocationRelativeTo(null);
        bArt.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

   
    private void activarBtn(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_activarBtn
       ifWindowsOpen.ventaOpen=false;
       ifWindowsOpen.activaBotones();
    }//GEN-LAST:event_activarBtn

    public static void newventa()
    {
        if(isNewVenta)
        {
            tablaVenta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                tablaVenta.setModel(Session.lineaVent=new javax.swing.table.DefaultTableModel(
                    new Object [][] {

                    },
                    new String [] {
                        "Codigo", "Descripción", "Precio", "Cantidad", "Monto"
                    }
                ) {
                    boolean[] canEdit = new boolean [] {
                        false, false, false, false, false
                    };

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
                isNewVenta=false;
        }
    }
    private void llenarTabla(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_llenarTabla
        tablaVenta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            tablaVenta.setModel(Session.lineaVent=new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Codigo", "Descripción", "Precio", "Cantidad", "Monto"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
        
        BRO.lineaVenta.restaurarVenta(DAO.ventaActual.getCurrentSale(Session.cnx));
    }//GEN-LAST:event_llenarTabla

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarVenta;
    public static javax.swing.JLabel cantArticulos;
    private javax.swing.JLabel fc_venta;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel montoVenta;
    public static javax.swing.JTable tablaVenta;
    public static javax.swing.JTextField txt_codigo;
    private javax.swing.JLabel us_venta;
    private javax.swing.JPanel user_venta;
    // End of variables declaration//GEN-END:variables
}
